// This file was automatically generated by the Juno CLI.
// Any modifications may be overwritten.

// @ts-expect-error any
export const idlFactory = ({ IDL }) => {
  return IDL.Service({ 'build_version' : IDL.Func([], [IDL.Text], ['query']) });
};
// @ts-expect-error any
export const init = ({ IDL }) => { return []; };